runtime: python39

env_variables:
  ROBOFLOW_API_KEY: "OCYzLwdUcqDtypAh0OYT"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
